const ROLES = {
  FIELD_OPERATOR: 'FIELD_OPERATOR',
  VERIFYING_OFFICER: 'VERIFYING_OFFICER',
  DISTRICT_EXPERT: 'DISTRICT_EXPERT',
  DISTRICT_ADMIN: 'DISTRICT_ADMIN',
  CHIEF_AUDITOR: 'CHIEF_AUDITOR',
  CITIZEN: 'CITIZEN',
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
};

const DOCUMENT_STATUS = {
  RECEIVED: 'RECEIVED',
  STORED: 'STORED',
  QUEUED: 'QUEUED',
  PROCESSING: 'PROCESSING',
  EXTRACTED: 'EXTRACTED',
  VALIDATING: 'VALIDATING',
  COMPLETED: 'COMPLETED',
  VALIDATED: 'VALIDATED',
  REVIEW_REQUIRED: 'REVIEW_REQUIRED',
  PENDING_REVIEW: 'PENDING_REVIEW',
  ESCALATED: 'ESCALATED',
  FAILED: 'FAILED',
};

const DOCUMENT_TYPES = {
  PATTA: 'PATTA',
  CHITTA: 'CHITTA',
  ADANGAL: 'ADANGAL',
  SALE_DEED: 'SALE_DEED',
  LAND_REGISTER: 'LAND_REGISTER',
  CADASTRAL_MAP: 'CADASTRAL_MAP',
  FMB_SKETCH: 'FMB_SKETCH',
  VILLAGE_SKETCH: 'VILLAGE_SKETCH',
  SETTLEMENT_REGISTER: 'SETTLEMENT_REGISTER',
  UNKNOWN: 'UNKNOWN',
};

const STAGE_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  FLAGGED: 'FLAGGED',
};

const PIPELINE_STAGES = [
  { stageNumber: 1, name: 'Document Ingestion' },
  { stageNumber: 2, name: 'Image Enhancement' },
  { stageNumber: 3, name: 'Document Classification' },
  { stageNumber: 4, name: 'Layout Analysis' },
  { stageNumber: 5, name: 'Multilingual OCR' },
  { stageNumber: 6, name: 'AI Entity Extraction' },
  { stageNumber: 7, name: 'Record Cross Validation' },
  { stageNumber: 8, name: 'GIS Spatial Validation' },
  { stageNumber: 9, name: 'Discrepancy & Risk Analysis' },
  { stageNumber: 10, name: 'Human Verification Routing' },
];

const DISCREPANCY_TYPES = {
  OCR_LOW_CONFIDENCE: 'OCR_LOW_CONFIDENCE',
  AREA_MISMATCH: 'AREA_MISMATCH',
  BOUNDARY_MISMATCH: 'BOUNDARY_MISMATCH',
  SURVEY_NUMBER_MISMATCH: 'SURVEY_NUMBER_MISMATCH',
  SURVEY_MISMATCH: 'SURVEY_MISMATCH',
  OWNER_NAME_MISMATCH: 'OWNER_NAME_MISMATCH',
  OWNER_MISMATCH: 'OWNER_MISMATCH',
  VILLAGE_MISMATCH: 'VILLAGE_MISMATCH',
  TALUK_MISMATCH: 'TALUK_MISMATCH',
  DISTRICT_MISMATCH: 'DISTRICT_MISMATCH',
  PARCEL_NOT_FOUND: 'PARCEL_NOT_FOUND',
  REGISTRY_MISMATCH: 'REGISTRY_MISMATCH',
  DUPLICATE_RECORD: 'DUPLICATE_RECORD',
  LOW_CONFIDENCE: 'LOW_CONFIDENCE',
};

const SEVERITY_LEVELS = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
};

const RISK_LEVELS = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
};

const DISCREPANCY_STATUS = {
  OPEN: 'OPEN',
  UNDER_REVIEW: 'UNDER_REVIEW',
  RESOLVED: 'RESOLVED',
  WAIVED: 'WAIVED',
  REJECTED: 'REJECTED',
};

const CASE_STATUS = {
  PENDING_REVIEW: 'PENDING_REVIEW',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  ESCALATED: 'ESCALATED',
  // Backward compatibility aliases
  NEW: 'PENDING_REVIEW',
  UNDER_VERIFICATION: 'UNDER_REVIEW',
  EXPERT_REVIEW: 'UNDER_REVIEW',
  RESOLVED: 'APPROVED',
  SEALED: 'APPROVED',
};

const CASE_DECISIONS = {
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  ESCALATED: 'ESCALATED',
  PENDING: 'PENDING',
};

const CASE_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
};

const AUDIT_ACTIONS = {
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  DOCUMENT_STORED: 'DOCUMENT_STORED',
  PROCESSING_STARTED: 'PROCESSING_STARTED',
  STAGE_COMPLETED: 'STAGE_COMPLETED',
  OCR_COMPLETED: 'OCR_COMPLETED',
  ENTITY_EXTRACTION_COMPLETED: 'ENTITY_EXTRACTION_COMPLETED',
  EXTRACTION_COMPLETED: 'ENTITY_EXTRACTION_COMPLETED',
  VALIDATION_COMPLETED: 'VALIDATION_COMPLETED',
  GIS_VALIDATED: 'GIS_VALIDATED',
  GIS_VALIDATION_COMPLETED: 'GIS_VALIDATED',
  DISCREPANCY_DETECTED: 'DISCREPANCY_DETECTED',
  DISCREPANCY_CREATED: 'DISCREPANCY_DETECTED',
  CASE_CREATED: 'CASE_CREATED',
  CASE_ASSIGNED: 'CASE_ASSIGNED',
  CASE_APPROVED: 'CASE_APPROVED',
  CASE_REJECTED: 'CASE_REJECTED',
  CASE_ESCALATED: 'CASE_ESCALATED',
  RECORD_SEALED: 'RECORD_SEALED',
};

const DEMO_SCENARIOS = {
  CLEAN_RECORD: 'CLEAN_RECORD',
  LOW_CONFIDENCE: 'LOW_CONFIDENCE',
  OWNERSHIP_CONFLICT: 'OWNERSHIP_CONFLICT',
  GIS_AREA_MISMATCH: 'GIS_AREA_MISMATCH',
  DUPLICATE_RECORD: 'DUPLICATE_RECORD',
  BOUNDARY_CONFLICT: 'BOUNDARY_CONFLICT',
};

module.exports = {
  ROLES,
  DOCUMENT_STATUS,
  DOCUMENT_TYPES,
  STAGE_STATUS,
  PIPELINE_STAGES,
  DISCREPANCY_TYPES,
  SEVERITY_LEVELS,
  RISK_LEVELS,
  DISCREPANCY_STATUS,
  CASE_STATUS,
  CASE_DECISIONS,
  CASE_PRIORITY,
  AUDIT_ACTIONS,
  DEMO_SCENARIOS,
};
